name: Ionic In Action
markdown: kramdown
#highlighter: pygments
excerpt_separator: <!--more-->
gems: [jekyll-paginate]
paginate: 10
paginate_path: "blog/page:num"
permalink: "/blog/:title"
url: http://ionicinaction.online/
